import Link from "next/link";

export default function InterviewerPage() {
  return (
    <main className="home-page">
      <header className="home-header">
        <p className="eyebrow">AI Interviewer reference application</p>
        <h1>Choose an interview journey</h1>
        <p>
          Create and schedule an interview, or open a candidate invitation.
          Production products provide their own branding around these APIs.
        </p>
      </header>
      <div className="product-grid">
        <article className="product-card">
          <p className="product-label">Recruiter flow</p>
          <h2>Create and schedule</h2>
          <p>Configure the role, interview design, candidate and policies.</p>
          <Link className="button primary" href="/interviewer/setup">
            Create interview
          </Link>
        </article>
        <article className="product-card">
          <p className="product-label">Candidate flow</p>
          <h2>Attend an interview</h2>
          <p>Use the secure invitation URL generated by the recruiter flow.</p>
          <span className="form-note compact">
            An invitation is required
          </span>
        </article>
      </div>
    </main>
  );
}
